pipeline{
	environment {
        
        VERSION = "1.1.1"
        REGISTRY = 'test/nodejs'
        REGISTRY_CREDENTIAL = 'conatiner-registery'
    }
	agent {
        kubernetes {
            defaultContainer 'jnlp'
            yamlFile 'build.yaml'
        }
	}
	stages{
		stage('Docker Build') {
            steps {
                container('docker') {
			sh "service docker start"
                    sh "docker build -t ${REGISTRY}:${VERSION} ."
                }
		    container('docker') {
                    withDockerRegistry([credentialsId: "${REGISTRY_CREDENTIAL}", url: "https://auh.ocir.io"]) {
                        sh "docker push ${REGISTRY}:${VERSION}"
                    }
                }
		    container('helm') {
                    sh "helm version"
                }
            }
        }
		stage("test"){
			steps{
			nodejs(nodeJSInstallationName:'nodejs'){	
			   sh "npm install"
			   sh "npm run build"
				script {
				
				   withSonarQubeEnv("test-npm") {
				   sh "${tool("sonarqube-container")}/bin/sonar-scanner \
				   -Dsonar.projectKey=test-npm  \
				   -Dsonar.sources=. \
				   -Dsonar.css.node=. \
				   -Dsonar.host.url=http://129.151.158.98:9000  \
				   -Dsonar.login=41986a4b64f343f848e8ecd65dbfabd6d12b0b62"
				       }
				}
		          // sh "docker -v"
			}	
			}
			
			
			
		}
 //		stage("sonarqube analysis"){
//			
//			steps {
//			       script {
//			       def scannerHome = tool 'sonarqube-container';
//				   withSonarQubeEnv("test-npm") {
//				   sh "${tool("sonarqube-container")}/bin/sonar-scanner \
//				   -Dsonar.projectKey=test-npm  \
//				   -Dsonar.sources=. \
//				   -Dsonar.css.node=. \
//				   -Dsonar.host.url=http://129.151.158.98:9000  \
//				   -Dsonar.login=41986a4b64f343f848e8ecd65dbfabd6d12b0b62"
//				       }
//				   }
//			}
//  			steps{
// 				nodejs(nodeJSInstallationName:'nodejs'){
// 					sh "npm install"
//  					withSonarQubeEnv("SonarQube Scanner"){
 					
//   						sh "npm install sonar-scanner"
//  					} 				
// 				}
				
			
					
				  
//  			}
 		}
	
}
